name: release
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          submodules: true
          # Tags are needed to compute the current version number
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Build manylinux wheels
        uses: RalfG/python-wheels-manylinux-build@v0.3.3-manylinux2014_x86_64
        with:
          python-versions: 'cp36-cp36m cp37-cp37m cp38-cp38 cp39-cp39'
          # Necessary for setuptools_scm to read the version from Git
          system-packages: 'git-lfs'
      - name: Install tox
        run: |
          pip install --upgrade pip
          pip install tox
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
          TWINE_NON_INTERACTIVE: "true"
        run: |
          tox -e release
